# This input file contains all necessary configuration settings in order to
# setup the AMQP Middleware. Most of the parameters below come with default
# values. Settings that are not commented out MUST be provided by the user.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                           Cloudify Manager Inputs                           #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# The IP address of the Cloudify Manager.
manager_host: '127.0.0.1'

# The username and password of a Cloudify Manager user. This set of credentials
# is required during installation, as well as for resource identification needs
# later on. It is advised that a user with adequate rights is used (admin) in
# order to avoid configuration errors.
manager_username: 'admin'
manager_password: 'nEQSwrbNPz1w'

# The tenant the aforementioned user belongs to.
#manager_tenant: 'default_tenant'

# The endpoint of Cloudify Manager's RabbitMQ server. If left blank, defaults
# to `manager_host`.
#rabbitmq_host: ''

# Specifies the username and password to be used in order to connect to
# Cloudify Manager's RabbitMQ server.
#rabbitmq_username: 'cloudify'
#rabbitmq_password: 'c10udify'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                   User Inputs                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# By default, users are required to provide a name and an e-mail address in
# order to create a new account.
user_name: 'cloudify-lab'
user_email: 'cloudify-labs@gigaspaces.com'

# Alternatively, in case one wants to:
# 1. use an existing account or
# 2. install additional AMQP Middleware(s) under the same account,
# then `user_exists` must be set to `true`. In that case, an authentication
# token has to be provided. Tokens can be retrieved by executing `cfy local
# outputs` at an existing installation of the AMQP Middleware.
user_exists: true
user_token: 'b4804dee1cdc355b4872f0dd2519607cf5cdac5d722ee513ce170ebae9572155'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                              Cloud Credentials                              #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# This section allows users to automatically populate a new account with clouds
# upon registration. For that to happen, uncomment the desired cloud section
# and fill in the required cloud credentials. Note that regions, if applicable,
# must be specified by their region code and letter identifiers, as advertised
# by each cloud provider.
#
# For instance, in case of AWS:
#
# - US East (N. Virginia) -->  "us-east-1"
# - Asia Pacific (Tokyo)  -->  "ap-northeast-1"

credentials:
#  ec2:
#    title: 'EC2'
#    apikey: ''
#    apisecret: ''
#    region: ''

#  digitalocean:
#    title: 'DigitalOcean'
#    token: ''

 openstack:
    title: 'OpenStack'
    url: 'localhost/dashboard'
    username: 'admin'
    password: 'cloudify1234'
    tenant: 'admin'
#    region: ''  # optional
#    compute_endpoint: ''  # optional

#  azure:
#    title: 'Azure'
#    subscription_id: ''
#    certificate: ''

#  vcloud:
#    title: 'vCloud'
#    host: ''
#    username: ''
#    password: ''
#    organization: ''

#  vsphere:
#    title: 'vSphere'
#    host: ''
#    username: ''
#    password: ''

#  docker:
#    title: 'Docker'
#    host: ''
#    port: 4243
#    username: ''  # optional, in case of username/password authentication
#    password: ''  # optional, in case of username/password authentication
#    key_file: ''  # optional, TLS authentication
#    cert_file: ''  # optional, TLS authentication
#    ca_cert_file: ''  # optional, TLS authentication

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Security Section                              #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Users SHOULD NOT have to edit this section, unless custom connfiguration is
# in place regarding Cloudify Manager's external HTTP and internal APIs.

# Denotes whether SSL is enabled and the Cloudify Manager's certificate should
# be verified.
#manager_ssl_enabled: false
#manager_cert_verify: false

# If SSL is enabled, this should point to the bundle of CA certificates.
#manager_ca_certs: '/etc/ssl/certs/ca-bundle.crt'

# Denotes whether SSL is enabled for RabbitMQ, which is true by default, and
# points to the corresponding SSL certificate.
#rabbitmq_ssl_enabled: true
#rabbitmq_cert_public: '/etc/cloudify/ssl/cloudify_internal_cert.pem'